# Generated by Django 6.0.7 on 2026-07-11 13:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField()),
                ('risk_tier', models.CharField(max_length=20)),
                ('top_drivers', models.JSONField(help_text='List of top contributing features')),
                ('actionable_intervention', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('adviser', 'Academic Adviser'), ('welfare_officer', 'Welfare Officer'), ('dean', 'Dean of Student Affairs')], default='adviser', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='ews_users', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='ews_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_tier', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prediction_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='ews_api.predictionresult')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_index', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Gender', models.IntegerField(help_text='1 = Male, 0 = Female')),
                ('Age_at_Matriculation', models.IntegerField()),
                ('Marital_Status_Binary', models.IntegerField(help_text='1 = Married, 0 = Single')),
                ('Special_Needs_Status', models.IntegerField(help_text='1 = Yes, 0 = No')),
                ('Mother_Education_Level', models.IntegerField()),
                ('Father_Education_Level', models.IntegerField()),
                ('Mother_Occupation', models.IntegerField()),
                ('Father_Occupation', models.IntegerField()),
                ('First_Generation_Student', models.IntegerField(help_text='1 = Yes, 0 = No')),
                ('UTME_PostUME_Score', models.FloatField()),
                ('Secondary_School_Exit_Grade', models.FloatField()),
                ('Study_Mode', models.IntegerField(help_text='1 = Full-time, 0 = Part-time')),
                ('Faculty', models.CharField(choices=[('Sciences', 'Sciences'), ('Engineering', 'Engineering'), ('Arts', 'Arts'), ('Social_Sciences', 'Social Sciences'), ('Law', 'Law'), ('Medicine', 'Medicine')], max_length=30)),
                ('Year_of_Study', models.IntegerField(help_text='Year of Study (1-5)')),
                ('Non_Resident_Student', models.IntegerField(help_text='1 = Yes, 0 = No')),
                ('Hostel_Residency', models.IntegerField(help_text='1 = Residing in hostel, 0 = Off-campus')),
                ('School_Fees_Payment_Status', models.IntegerField(help_text='1 = Paid, 0 = Unpaid')),
                ('Fee_Arrears_Status', models.IntegerField(help_text='1 = Has arrears, 0 = No arrears')),
                ('Bursary_Scholarship_Status', models.IntegerField(help_text='1 = Recipient, 0 = Non-recipient')),
                ('Units_Registered_Semester_1', models.IntegerField()),
                ('Units_Passed_Semester_1', models.IntegerField()),
                ('Assessments_Sat_Semester_1', models.IntegerField()),
                ('Units_No_Assessment_Semester_1', models.IntegerField()),
                ('GPA_Semester_1_5pt', models.FloatField()),
                ('Pass_Rate_Semester_1', models.FloatField()),
                ('Units_Registered_Semester_2', models.IntegerField()),
                ('Units_Passed_Semester_2', models.IntegerField()),
                ('Assessments_Sat_Semester_2', models.IntegerField()),
                ('Units_No_Assessment_Semester_2', models.IntegerField()),
                ('GPA_Semester_2_5pt', models.FloatField()),
                ('Pass_Rate_Semester_2', models.FloatField()),
                ('CGPA_5point_Scale', models.FloatField()),
                ('GPA_Change', models.FloatField()),
                ('Dropout_Status', models.IntegerField(default=0, help_text='1 = Dropout, 0 = Non-Dropout')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ews_api.student')),
            ],
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='student_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='ews_api.studentrecord'),
        ),
    ]
